### ISSUE TITLE
Remove the word "image" from edit context

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#114]
Usually, "image" refers to a bitmap.  We should consistently use terms that do not imply bitmap, like "document," "drawing," or "painting" 

"Open an example image"   -> "open an example drawing"
"import image"  -> ??? Seems to actually import images, but since we can't *print* them, this may not be a good thing.

**Comment by techninja** [comment]
This issue was moved to evil-mad/robopaint-mode-edit#1
