### ISSUE TITLE
[ Feature Request ] Option to load paint on new sub-path instead of distance-based

### ISSUE THREAD

**Issue by gwygonik** [evil-mad/robopaint#118]
For certain artistic uses and to keep strokes as continuous as possible, it would be useful to be able to choose to reload paint on new sub-paths instead of the distance-based default which increments across sub-paths. While I believe this can be done in manual paint mode by first loading paint then stroking individual sub-paths, this can be quite time consuming with pictures that have many strokes, or are unable to be easily broken apart into separate paths.

However, as this may create a larger-than-normal number of paint reloads, it can wear down the paint quickly. This can be solved by adding the ability to select between a full reload or a dip reload (dip water, dip paint) after the initial full paint load. 

This process may increase the time it takes to paint a picture, but as an option it would be up to the user to decide which they prefer -- speed or stroke continuity.

I've successfully implemented the code to do the first bit -- reload on new sub-path -- but am unable to get preferences, UI elements, or dip option working correctly. I'm adding this item as a feature request so the folks who know what they're doing can weigh in. I'm more than happy to provide my code, but it's a hack. I'm also happy to work on it properly if I can get some knowledge assistance. :-)

The pic below was painted with my reload-on-new-sub-path code -- note all the sub-paths 1) start with fresh paint on the left and are continuous across the image, and 2) get slightly thicker as each sub-path does a full paint reload (a dip would suffice):

![wcb_perlin_new_1](https://f.cloud.github.com/assets/2564583/1649980/9d92ed9a-5a4e-11e3-93f6-5451a679b460.png)

**Comment by gwygonik** [comment]
Hey folks. I have this working in 0.9.2, though I haven't run that many SVGs through it. I'm going to get a fork of 0.9.2 proper and send a pull request. I'd ask that the changes be looked over and more sanity tests run. :smiley:

**Comment by techninja** [comment]
Wonderful! And good luck. Big changes are afoot, but this should continue to be useful and relevant as we move forward for more bot types support. Feel free and ask any questions about how things work or if you have any issues or need some testing here :) :+1:

**Comment by gwygonik** [comment]
Ok! Looks like I got all the options working -- stroke each path and full brush reload vs single dip vs double dip. I did NOT get translations (I'd have to Google translate). Will do a pull probably tomorrow night.

**Comment by techninja** [comment]
I'll take a look and see if I can get this in :)

**Comment by techninja** [comment]
Looking **_great_**! I'm going to do some minor cleanup to this and It'll be in the 0.9.6 bugfix release coming up. Will close this ticket when I'm done.
