### ISSUE TITLE
Paint Brush Tool 

### ISSUE THREAD

**Issue by RI0** [evil-mad/robopaint#122]
We have noticed that RoboPaint is missing an obvious tool : A Paint Brush

We would like this tool to be in addition to the Pencil Tool because it should be a little bit different from the pencil. We would like it to be set to 33% opacity by default and have an adjustable smoothing function so drawing is more fluid and brush-like. We find this really hard with a touchpad or a mouse. We think the brush shape should also be round so a mouse click dot should be a circle not a square. It would be great if the brush width could also start at about 33. 

Paint Brush Tool
Proposed Options and Starting Values 

Width : 33
Opacity : 33%  
Smoothing : 33%
Brush Shape : Round 

We love the WaterColorBot and RoboPaint - Thank you for making it better and better.

**Comment by techninja** [comment]
Closing this as `wontfix`. The pencil precision is a separate issue.
