### ISSUE TITLE
Apparent loss of connectivity, not detected or handled.

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#127]
A user (Mike S.) sent in the following report:
"[I] was testing with RoboPaint RT and RoboPaint (on Windows 8.1 after installing the USB driver). RoboPaint
RT works as expected. However, when RoboPaint starts, the carriage initializes (makes a noise) and I receive no error messages about connecting. I'm able to use the program, but when I click Start (or any of the other controls), nothing happens on the Bot. When it "paints," I can see the little cursor moving where the strokes would be, but nothing happens on the Bot. I've restarted my machine, but consistently, RT works where the non-RT version doesn't."

This report sounds like the computer has lost its connection to the EBB.  (I can replicate this issue by disconnecting the USB cable-- but obviously the cable is good, since RoboPaint RT is working.)  IIRC, previous versions of RoboPaint would detect if the EBB was not connected, and had some facility for reconnecting.

**Comment by techninja** [comment]
Since a version released around May 2015, node-serialport has been acting much better, and properly recognizes disconnect as well as it ever did. If more similar issues arise after the next release, we should re-open.
