### ISSUE TITLE
Add progress and status indicator when moving out of edit mode

### ISSUE THREAD

**Issue by techninja** [evil-mad/robopaint#143]
For long/complex graphics, many elements may need to be converted/adjusted (as in #139), therefore we need to intercept the Edit mode unload, show a modal window for conversion status and full progress percentage.

See https://github.com/evil-mad/robopaint/blob/master/resources/scripts/robopaint.method-draw.js#L86

**Comment by RI0** [comment]
My sister suggested this : what if the progress image was an animation of a paintbrush swirling around in paint or possibly mixing two colours together.

**Comment by techninja** [comment]
Um......sure, why not. Unfortunately we don't have any designers/artists on staff, know anyone that could draw the animation?

**Comment by techninja** [comment]
Good news everyone! in the next version, Paper.JS handles pretty much **_any_** SVG path conversion for us, so we don't have to do it on exit! All the slow code that needed this has been removed.
