### ISSUE TITLE
Park, Motor, Raise/Lower brush not working

### ISSUE THREAD

**Issue by taliesan** [evil-mad/robopaint#154]
Downloaded 0.9.0 and 0.7.5 for Mac. Using OSX 10.8.5. It prints, but the buttons for park, lower brush, and unlock motors don't do anything.

I can get it working fully from a Windows machine, so I know the watercolor printer works.

**Comment by techninja** [comment]
I'm going to take a guess that since we haven't heard anything back in a while this is managed or a workaround found. Feel free to reopen if this is not the case.
