### ISSUE TITLE
Better source for mode icons

### ISSUE THREAD

**Issue by docprofsky** [evil-mad/robopaint#170]
During the code [walkthrough](https://github.com/evil-mad/robopaint/issues/165) a lack of good mode icons was discussed. One alternative is http://thenounproject.com/. We can discuss if we need to use this here.

**Comment by docprofsky** [comment]
Modes now provide their own graphic (SVG or bitmap) to use as an icon. Unless you think this still needs resolution I advise this issue be closed.

**Comment by techninja** [comment]
Yup, that was the intent.
