### ISSUE TITLE
Roll 0.9.5 feature/bugfix release

### ISSUE THREAD

**Issue by techninja** [evil-mad/robopaint#185]
_This issue is a placeholder for the work and discussion behind the next release and should act as a tracker for any release delays or important points about the build not already ticketed._

This release is intended to focus on missing/incomplete core features and some likely new improvements as well. Ignoring anything Pie in the sky, some very hot-topic issues that have been bumbling around and usually have a bit of work done for quite some time include:

* Complete translation, from install, to color selection, to modes. As of 0.9.2, we only have 2 language translations from English, and then only of the RP Main window and settings pages.
  * Thanks to hard work by @rogerfachini, colorset translation is in final stages of PR along with some much improved thinking behind what a colorset media is, allowing for some very good ideas around Pen/Eggbot support
  * I've already added (untested) .po translation support to the Windows install file, it should be a short skip to get some automated translations of these strings and get that going much better.
  * Rumor has it that @docprofsky is working on an automated translation script to quickly populate our translation string sets.
  * No real work has been done to translate modes, though I suspect @rogerfachini's got plans as soon as we wrap up #181 
* #130 EggBot support has always been _somewhat_ there as I've always had it in mind when developing, but lots more work needs to be done. If we decide we can put together everything that proper EggBot support needs (swap naming conventions/plural, change settings pages, allow for selecting "pen" based colorsets, or even wax? #70), we should prioritize it as it opens RoboPaint up to a wider audience of established users.
* Lowest on the priority list is remote CNCServer support. This is cool and allows for a much more "remote printer" style of use, and is surprisingly useful and not far off from being complete. Though I don't see it as a very common use case without some of the setup barriers lowered a bit. Not to mention network throughput on bad WiFi connections can seriously detract from general print quality while buffering and will need to be re-worked at a lower level than is likely doable within scope of current plans.

And as always I'm open to discussion, though to try to keep focus and actually finish the things we started, I can't really allow much in the way of work on additional modes, though I've been toying with some locally in my spare time, we'll need to look at the bigger picture for those once we get the core issues and support managed.

**Comment by techninja** [comment]
### 0.9.5 Status Report:
There's a chance that the holidays (and the coming onslaught of First Robotics, which Roger and Schuyler both participate in) are likely to utterly mess up our chances for a big collaborative release on time, or it may simply limit what features get in. 

* @rogerfachini is hard at work on #199, which is surprisingly difficult/huge (companion issue #186, #129). I'm likely going to have to come in and help, though the hope is that the basic template of how mode translations work setup and merged to master before actual completion, along with @docprofsky's translation script to build out missing translation files, and new strings.
* #137 (Remote server) has fallen by the way side, and it likely needs a companion wiki page on setting up a remote CNC server if we expect it to be an option when starting RoboPaint. Considering the lowered use case, unless I hear any different this may move off to 0.9.7.
* #130, #70 (Eggbot support) has been a thorn in my side as I work to figure out the best way to do this. I want to do it **_right_**, but I don't want to add too much work.
  * The conversation I've laid out in the later comments of that issue is complicated, but hopefully 100% clear to the user when implemented: Allowing them to select on first run what bot they're using, then leading them through in the setup screen what implement, pen set/color set is to be used, and on what media base.
  * This opens up the ability for modes to decide how to work based on a large set of configuration information instead of the mess of incomplete assumptions we run on now.
  * This is a **big** priority of mine, but unfortunately requires a better knowledge of User Interface design than I have. :cry:. I've discussed (and totally confused) @rogerfachini & @docprofsky, so I hope to do some white-boarding today and get further than I currently have. 
* #89 (Water painting detection) is a silly issue that should have been done a while ago and can likely be done and tested in an afternoon.

**Comment by techninja** [comment]
Somewhat as expected, I'm pushing this release up another two weeks. I'm not getting any feedback on UI adjustments in #130, and haven't heard any updates from @rogerfachini or @docprofsky on translation status. Hopefully we have what it takes to kick this together and get it going before a single month delay becomes a 7 months delay :worried: :sweat_drops:

**Comment by rogerfachini** [comment]
Work is slow for me, FRC has started and that is eating up a large amount of my time. The main bottleneck with translations for me is finding those DOM locations. I could really use some help with finding the locations; What I might do is get the other modes translated and when they are done we will just have the edit mode in our way. The fact that the filesystem on one of my drives got turned into a pile of goo a couple of days ago hasn't been helping me have more time to work on this though  :(

**Comment by oskay** [comment]
If it's becoming blocking, I'd advise moving #130 to the next milestone. We're all stuck in FRC mode right now, so available time is... variable. :)

**Comment by techninja** [comment]
@rogerfachini: As I hope I made clear in a few of our meetings, I wanted you to get the base work completed and pushed to your branch, and I can really take the grunt work from there. Now that I see that DOM work has been pushed, I can likely flush it out in a copy of your branch and get the whole thing into master without your PR or using too much of your time.

Of course I'll still likely need some input from @docprofsky if I can get it on the translation automation, but there's a chance I can man-handle the python necessary to update everything we need... or just re-do it in a more node native scripting language :disappointed_relieved:.

And @oskay, I'll review your input and Do what I can, though #130 will be staying in it's own branch for a while considering how big it is just in case it doesn't make it in by the deadline.

And don't worry guys, by this time Next Year, I'm sure to be up to my ears in @makersylvia's FRC fun :grinning:

**Comment by techninja** [comment]
*0.9.5 Status Report #2:*
* Release has now been moved ahead a week, but should come sooner rather than later.
* Mode Translation is happy and in the bag!
* #130 & #70 have been moved to 0.9.7
* All other remaining tickets in the milestone should be set for completion by the deadline

**Comment by techninja** [comment]
@oskay Ok. Release has been drafted and tested on three systems! I have yet to fill out the notes, but I'll get to that once you sign the release :)

**Comment by oskay** [comment]
Release signed.

**Comment by techninja** [comment]
Completed and released!

https://github.com/evil-mad/robopaint/releases/tag/v0.9.5-2015.01.25
