### ISSUE TITLE
Add translation capabilities to modes

### ISSUE THREAD

**Issue by RI0** [evil-mad/robopaint#186]
I noticed that some of the mouse over text on the home page does not display in French or Spanish in this version. Top menu and the large circular buttons.

**Comment by techninja** [comment]
Done and completed Through my last PR #202. This means a whole new set of translations to be made in a whole new set of files, but at least we have a clean starting point. @RI0, feel free and take a look in the `_i18n` folders within the [modes folder structure](https://github.com/evil-mad/robopaint/tree/master/resources/modes) and feel free to submit a PR for any translation adjustments/improvements you might have :)
