### ISSUE TITLE
Saving files broken in electron builds

### ISSUE THREAD

**Issue by rogerfachini** [evil-mad/robopaint#220]
When choosing the 'save svg' option in the electron-built versions, the pop-up window will be the 'Open File' window, making saving images impossible! Will submit a PR as soon as my dev environment is set up.

**Comment by techninja** [comment]
I'm actually going to handle this and any other Electron bugs inside the original #215 to ensure that the transition is basically transparent. There really are very few specific interactions we did to Nw.js, but this is definitely one of them. Any native dialogs had their own API that now differs considerably.
