### ISSUE TITLE
overshooting path

### ISSUE THREAD

**Issue by forresto** [evil-mad/robopaint#229]
Seems to overshoot every path by ~1cm:

![img_20150927_114943](https://cloud.githubusercontent.com/assets/395307/10125140/fb553c6c-6537-11e5-80c7-1ffa76f91d09.jpg)

Is this a Robopaint or firmware bug?

**Comment by techninja** [comment]
Hello there @forresto! The overshoot in RoboPaint is a setting made to help painting with bent brushes, but is terrible for pens. Go to the gears (Settings) page, and find the "overshoot" option, and you should be able to set it to 0. If you're having trouble I'd be happy to provide you with screenshots. Good luck!

**Comment by forresto** [comment]
Right! Feature not a bug. Thanks.

**Comment by techninja** [comment]
Yep! Next version will turn that off by default for pen/pencil mode. Thanks for the mode suggestion by the way. Feel free to suggest or bug us for anything you might need, we're only as active as our community!
