### ISSUE TITLE
Path fill: Fix secondary fill angle at 90 degrees to first fill (even when angle is random)

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#239]
Feature suggestion! 

(I love randomized angle fill; this will make it more useful.)

**Comment by techninja** [comment]
I think you mean set fill angle to 90degrees from first fill for RANDOM, because it does do 90deg hatch set _without_ random. Should be a relatively easy fix now that I think about it.

**Comment by oskay** [comment]
Yes.
