### ISSUE TITLE
Add option for insetting fills

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#240]
When drawing or painting, Hatch and spiral fills can often intersect with or exceed the boundaries of the original area to be filled. We compensate potentially for this by performing an "inset" operation on the area to be filled before filling it with a hatch.  

http://wiki.evilmadscientist.com/Creating_filled_regions#Using_Hatch_and_Inset_together

It would be nice to have an option to inset fills in RoboPaint, with an option in the settings to adjust the amount of inset.

**Comment by techninja** [comment]
What range values do you want for the dropdown? I'm assuming we'd want negative inset as well.

**Comment by oskay** [comment]
Not sure-- also not sure how easy or hard this is. This may be a little tricky to find a good set-- for pen/pencil you might want a much finer range of inset values than you want with a brush.  Perhaps powers of 2, for some units?  0, 1, 2, 4, 8, 16, 32, 64?

I don't immediately see a use case for "outset." Perhaps we should leave out negative values.

**Comment by techninja** [comment]
Huh. I'm kind of flabbergasted, but not only is my modularity _**off the hook**_, it's damn extensible too!

![robopaint _022](https://cloud.githubusercontent.com/assets/320747/11087027/9bac8d28-880b-11e5-9868-b380e7085b2a.png)

Sure, I had already simplified the working JS Clipper code to do path offsets, but to be able to simply drop in a path preprocessor, setting, and brand new library without batting an eye and less than afew hours work to make something that feels like it completely changes the game?! This is crazy. This looks like how it's _always supposed to have looked_. **GEEZ.**

![robopaint _023](https://cloud.githubusercontent.com/assets/320747/11087069/de267f56-880b-11e5-94ac-43f059ae73cd.png)

Up to 64 seems a very safe range, though I suspect you'll want to mess with it. The fills completely disappear for the ALL the objects in the preview at that point. Here's what the earth looks like with 64 unit inset:

![robopaint _026](https://cloud.githubusercontent.com/assets/320747/11087124/4c70e26c-880c-11e5-98f2-60ec5eb1ec5b.png)

I guess I'll finalize the text and push it out. While I'm at it I'll see if I can't get a bit closer to the Inkscape smooth fill shape.

**Comment by oskay** [comment]
_Damn_ that looks nice!

**Comment by EmbeddedMan** [comment]
Agreed! This interface is looking super crazy awesome.

**Comment by techninja** [comment]
This is done. Will be in next build.
