### ISSUE TITLE
Settings window: Modes toggle buttons are hard to actuate

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#243]
Tested on Mac. Some of the mode buttons are very challenging to press-- they seem only intermittently responsive.

**Comment by techninja** [comment]
The way they're made likely has their two clickable elements moved around a bit. I'll verify and attempt a fix.

**Comment by techninja** [comment]
Hmmmmmmm
![clicktest](https://cloud.githubusercontent.com/assets/320747/12095688/636680ce-b2c5-11e5-84c8-ed08eff7103a.gif)

Not quite seeing the problem. :confused: 

This was captured with "[LICECap](http://www.cockos.com/licecap/)" (_**terrible name**_, great app), with click animation on. See if you cant reproduce and record it and I'll see if i can tell what's going on.

**Comment by oskay** [comment]
The problem is only in the _Modes_ panel.

**Comment by oskay** [comment]
![robopaintmodes](https://cloud.githubusercontent.com/assets/1009180/12096009/3c8d75b4-b2c7-11e5-8616-02fc94b805db.gif)

**Comment by techninja** [comment]
Aha! That is actually on purpose! Core modes are not switchable. Notice they're somewhat faded to denote their disabled property. The idea being that core modes represent something that is expected and not directly toggle-able. I've been waffling on what to actually do for this, and tried it with having everything be adjustable, but you still kind of need them, so I just went with "disabled == core".. course it doesn't quite make sense for spiral... Eh. It's all a test.

**Comment by oskay** [comment]
Ugh. You *do* realize that this means that they can't be turned on either, right?

![robopaintmodes2](https://cloud.githubusercontent.com/assets/1009180/12096589/26209b9a-b2cb-11e5-9915-8ecaff396c97.gif)

**Comment by oskay** [comment]
Related issue: The "Reset" button turns all of the modes off.  (This is probably not the intended effect.)

Once the modes are off, the core modes _cannot_ be enabled, except by quitting and restarting RoboPaint.

**Comment by oskay** [comment]
Also: Is there any reason that the core modes must be left visible?  I can imagine situations where one might want to only allow (for example) the remote print mode.

**Comment by techninja** [comment]
Aha!! THAT is the real bug there! Otherwise you wouldn't be able to disable them in the first place. What do you recommend (besides fixing the reset all mode disabled bug)?

**Comment by techninja** [comment]
Yea, makes sense. We don't technically need the disabled locking. I'll just remove that and a user could choose to only have remote paint visible.. though clicking on a quick load image will still load the print mode

**Comment by oskay** [comment]
Yes, disabling the modes is how I came across this. :)

Allowing you to disable any should be a great solution.... and auto-loading a mode like that when you ask for it sounds like a reasonable side effect.

**Comment by techninja** [comment]
![bug-vs-feature](https://cloud.githubusercontent.com/assets/320747/12136131/7801ff38-b3f9-11e5-9778-30d737896893.jpg)
