### ISSUE TITLE
Document API option to tell RoboPaint that it's ready to paint

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#244]
Following up on #224, this option allows the remote (or, programmatic) user of RoboPaint to allow new sessions to be opened without manual intervention.

**Comment by techninja** [comment]
Took a second to look, forgot about the repository move! Does this cover us?
https://github.com/evil-mad/robopaint-mode-remote/blob/master/API.md#ready-state-override

**Comment by oskay** [comment]
Yes, indeed! 

Is it OK if I replace the old API document ( https://github.com/evil-mad/robopaint/blob/master/resources/api/API.md ) with a note indicating where the current documentation can be found?

**Comment by techninja** [comment]
I don't think it exists in the [paperjs branch](https://github.com/evil-mad/robopaint/tree/paperjs). Maybe a new file? Or an addendum in the main readme would make sense.

I believe I'll be merging the paperjs branch to master as soon as we're good to launch the beta. IT IS, _the future_!

**Comment by oskay** [comment]
My concern is that we *do* have this older document, that has out of date API information. That document should be removed, and if we remove it, it would be better to leave a "forwarding address" than to have a dead link.

**Comment by techninja** [comment]
A valid concern. Though the document won't belong or exist there, I don't have a problem putting in a stub, I'm just curious where it might be linked that would require this?

**Comment by oskay** [comment]
As of a couple of hours ago, it wasn't (so far as I know) clearly linked from anywhere-- an oversight. We do have some links to it here and there, and Google knows about it as well.

**Comment by oskay** [comment]
Let's consider this _really_ closed now.
