### ISSUE TITLE
Save state of Remote Print "Don't reset readiness" switch?

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#245]
To reproduce issue:
1. Enter remote paint mode
2. Toggle "Don't reset readiness" mode to true
3. Go to home screen
4. Go back to remote paint mode. "Don't reset readiness" toggle is no longer true. 

It seems as though this setting should be saved. Thoughts?

**Comment by techninja** [comment]
This issue was moved to evil-mad/robopaint-mode-remote#1

**Comment by techninja** [comment]
Questions regarding only mode functionality should live in the mode specific repo :)

Should probably include links to all of them in the readme.
