### ISSUE TITLE
Spiral paints Mona Lisa after choosing a different photo

### ISSUE THREAD

**Issue by forresto** [evil-mad/robopaint#264]
Chose a different photo, it traced it, looks good... do print and it took a looong time to figure out it was actually painting Mona Lisa.

**Comment by oskay** [comment]
We have had one additional report of this; not sure what the root cause is.  

However, this may not be the best place to discuss it-- perhaps we should open an issue directly at: https://github.com/techninja/robopaint-mode-spiral/issues

**Comment by forresto** [comment]
Moved to https://github.com/techninja/robopaint-mode-spiral/issues/3
