### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by docprofsky** [evil-mad/robopaint#276]
We should add an issue template to make it clear what is needed for reporting a bug or requesting a feature.

Here is my suggestion for a template
```
### What is the problem?

### What do you expect to happen or want to happen?

### How can this be reproduced?
Include any files necessary by zipping them and attaching them to this issue.
```

**Comment by techninja** [comment]
Because this is handled by files in the repository, you can just go ahead and open a pull request for this :smile: 

Closing.
