### ISSUE TITLE
Feature / Vertical plotter

### ISSUE THREAD

**Issue by alexiscz** [evil-mad/robopaint#293]
Hi guys, 

I don't know if someone already tried to did that but I am currently trying to build a vertical plotter running on raspberry bi and using the EBB board.  
EBB board is really a nice product and I am pretty sure it will be a nice use case to build a vertical plotter with it.
I am trying to build something generic so your inputs are very welcome. 

What I am currently doing : 
- Create a bot config in the CNC server with a new type (such as cartesian or vplotter)
- Create a new function in cncserver.utils to convert points for a vertical plotter 
- Create new parameters for vertical plotter in the conf window

Let me know if you have other ideas. 

Thanks,

A

**Comment by oskay** [comment]
I should note that there are many types of vertical plotters. Some of them are driven as XY, some are driven as (a+b,a-b), and some are driven in yet other ways. I think that what you are referring to here is a vertical "hanging-V drawing machine" -- but the "vertical" part of it is neither necessary nor sufficient to describe what it is that you are after.

**Comment by alexiscz** [comment]
Hey Oskay you are in all repositories ;) (cf. CNCserver)
I forgot this information, but you are right I am referring to a vertical hanging drawing machine. 
This is why, as we have already discussed on the cncserver repository, I would like to add some functions to convert points from a cartesian system to a polar system.

**Comment by oskay** [comment]
I imagine that this should be done within cncserver, not robopaint. If cncserver supports this type of motion with an .ini file, then Robopaint support is trivial.

**Comment by techninja** [comment]
Yup :+1: 
We've discussed it a bit and with some kind of consensus there, can make it a feature. PRs are always welcome of course, though development is pretty slow while I'm in the process of moving. Might just have a bugfix release out soon, but no real movement on features. I'm going to close this for the sake of housekeeping as support lies entirely within the realm of cncserver (it simply exposes the aspect ratio and a 2D drawing surface to RP and RP doesn't care how it manages to do that).

**Comment by oskay** [comment]
Agreed 100%. Thank you, @techninja.
