### ISSUE TITLE
v 2.1.0 (Mac) shows as damaged

### ISSUE THREAD

**Issue by oskay** [evil-mad/robopaint#295]
Attempting to open this on the Mac shows the infamous "this file is damaged" dialog, which usually indicates that the application is not properly signed.

**Comment by techninja** [comment]
Weird! I'm getting a new macbook charger very soon so I should be able to verify, it's possible the upload failed, but I'm pretty sure nothing funny has happened to the signing to mess this up in the intervening months. Will check tonight.

**Comment by techninja** [comment]
El Capitan, downloaded fresh DMG, extracted and installed with no issues. App runs fine. I guess time to upgrade the OS again? 😕

**Comment by oskay** [comment]
Yes, I think that's it. I believe that you need to be on Sierra or later to sign currently-accepted packages.

**Comment by techninja** [comment]
Oh sheesh. When the charger comes I'll get the upgrade going

**Comment by techninja** [comment]
OK! So.. apparently Apple is a terrible company and hates loyal people who appreciate their hardware. My only macbook laptop from ~2009 is now on the no longer supported list, and will be arbitrarily denied OS software updates now, even though it seems to run beautifully on el capitan. 

https://www.intego.com/mac-security-blog/what-to-do-if-your-mac-cant-run-macos-sierra/

...now what?

**Comment by techninja** [comment]
I mean this with full sincerity: As long as your local XCode is updated with the correct certs, building, signing and making releases is vastly more tame than it has been in the past. Lemme know what options you think we've got and we can chat. Maybe you've got an older yet newer macbook laying around 😆

**Comment by oskay** [comment]
Well... that computer *is* 8 years old....

I don't have any more recent computers lying around (recently recycled a bunch). It may be time to temporarily go back to having me sign the packages.

**Comment by docprofsky** [comment]
I am on 10.10, Yosemite, though I do not think this can help. I also have access to a PPC iMac.

**Comment by EmbeddedMan** [comment]
You can easily make a Mac in VirtualBox, and run the latest OS that way on your Windows or Linux machine. Would that help?

**Comment by techninja** [comment]
Yes, I suppose it will! I suppose I'll head down the rabbit hole. 🕳🐇

**Comment by techninja** [comment]
![screen shot 2017-12-07 at 6 59 49 pm](https://user-images.githubusercontent.com/320747/33749082-d7db7d02-db80-11e7-838f-5c1b72c63087.png)

UM... Might this be the problem?

**Comment by oskay** [comment]
Yup. Looks like you might need to renew that. :P 

The one on my computer is good to 2022.

**Comment by oskay** [comment]
Looks like the certificate in your name (on our account) is valid to Dec 07, 2018.

**Comment by techninja** [comment]
I think what matters here is that cert. I've downloaded the new one, but it isn't available as a signing identity. I sure love how clear as mud this always is. Thanks apple :rage3: 🍎  💥

**Comment by techninja** [comment]
Aha. Lucky me! [Upgrade is in fact possible.](https://www.youtube.com/watch?v=tZ6TomIhqcY)

**Comment by techninja** [comment]
FWIW: I've upgraded!... but I've yet to find the time to properly fix the signing cert, because as simple as you'd think it should be.. it is not. 😖

**Comment by oskay** [comment]
No, you wouldn't think it's simple. Having been through this a few times, I still need to look through the docs every time: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html

**Comment by lalo** [comment]
Any update on this issue?

**Comment by techninja** [comment]
@lalo Et Al: Sorry for the wait, life has been crazy as usual. I have my upgraded mac running, I hope to take another few hours soon and simply reset my local certificates (or try under a new user account) to get this working ASAP. Will likely get this out as RP 2.2.0 and a few other bugfixes and upgrades very hopefully before the end of the month.

**Comment by techninja** [comment]
Ok! I wouldn't believe it if I hadn't seen it myself, but I made a new mac appstore 3rd party distribution cert from this machine (something I was planning on doing anyway to get this on the mac appstore!), and I think it worked!!

@oskay Please test [this testing build](http://robopaint.tn42.com/RoboPaint_Mac_v2.1.0.dmg). If this works, then I can focus on wrapping up the rest of what's needed for this next release (bugfixes and security updates). WHEW.

**Comment by oskay** [comment]
I downloaded it and opened it. It gives a warning that it is from an "unidentified developer", but if you give it permission, it does open and connect.  

Is that using an Evil Mad Scientist certificate, or a different one?

**Comment by techninja** [comment]
@oskay Sorry for the wait, just got back from a work trip. That is strange that it says it's from an unidentified developer, this was signed with the new 3rd party distribution certificate, and gave no error. I'll run some diagnostics and attempt more verification as this should be cinched.

**Comment by oskay** [comment]
It's a partial success-- current MacOS will refuse to open any _unsigned_ package....

**Comment by techninja** [comment]
...huh. These are the two command suggested by apple to verify signatures.

```
shadow:build techninja$ codesign --verify --deep --strict --verbose=2 dist/RoboPaint.app/
--prepared:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--prepared:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--validated:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--prepared:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/RoboPaint Helper EH.app
--validated:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/RoboPaint Helper EH.app
--prepared:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/RoboPaint Helper NP.app
--validated:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/RoboPaint Helper NP.app
--prepared:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/RoboPaint Helper.app
--validated:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/RoboPaint Helper.app
--prepared:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--validated:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--prepared:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:/Users/techninja/web/robopaint/code/build/dist/RoboPaint.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
dist/RoboPaint.app/: valid on disk
dist/RoboPaint.app/: satisfies its Designated Requirement
shadow:build techninja$ spctl -a -t exec -vv dist/RoboPaint.app/
dist/RoboPaint.app/: rejected
origin=3rd Party Mac Developer Application: Evil Mad Science LLC (67VYYJK96Z)
```

Sooo, it verifies and it doesn't. Lovely. More digging is needed I guess 😢

**Comment by techninja** [comment]
@oskay Spent 2 hours on this. Learning:
- Developer ID application certs are restricted to the private keys/certificate signing request of the specific machine they were created on. When I upgraded, or when it expired, these broke for my local machine, and though I can download/install the Developer ID cert, it's **not** a valid signing identity because it's missing the private key.
- Only "Agents" (of which _there can be only **one**_) are allowed to create these, hence the insanity we had to jump through to get this working last time to get a private key from you.
- Developer ID certificate signing is really supposed to only be used for "development" level distribution, which. I think is wrong, so..
- Been working through [this incredible Mac App Store signing guide](https://mintkit.net/electron-userland/electron-osx-sign/guide/) to use the app id, distribution provisioning profile and distribution cert I made last time. This has yet to work in a way that I can call ready for testing, but will post back here ASAP if I get something promising.
- Sorry for the hassle and wait 😢

**Comment by oskay** [comment]
Any progress on this? There is a new batch of WaterColorBots starting to ship. ;)

**Comment by derrallg** [comment]
The testing build posted on January 30th worked for me. I was also getting the Damaged File prompt with the other version. I thought it was odd that the earlier version wasn't available to approve for download in the Security settings and with the update I was able to approve.

**Comment by jrheard** [comment]
FYI: i see this "damaged file" behavior when i try to run robopaint v 2.1.0 on mac os x version 10.14, on a macbook air. i followed the instructions in [this video](https://www.youtube.com/watch?v=3py0kgq95Hk)  to bypass that prompt, but when i try to run robopaint after that i see "The application 'RoboPaint' can't be opened", and a "problem report" window opens up. here is the information from that window:

```Process:               RoboPaint [77637]
Path:                  /Applications/RoboPaint.app/Contents/MacOS/RoboPaint
Identifier:            robopaint-main
Version:               2.1.0 (2.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RoboPaint [77637]
User ID:               501

Date/Time:             2018-10-18 12:45:19.263 -0700
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Anonymous UUID:        ACD8009C-DC18-666A-244D-2F0DAB75E88E

Sleep/Wake UUID:       48B77D20-27CF-4540-A3D0-13DAAF84A879

Time Awake Since Boot: 390000 seconds
Time Since Wake:       1300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/RoboPaint.app/Contents/MacOS/RoboPaint
  Reason: no suitable image found.  Did find:
	/Applications/RoboPaint.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: code signature invalid for '/Applications/RoboPaint.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework'

	/Applications/RoboPaint.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x1014b9000 -        0x1014b9ff7 +robopaint-main (2.1.0 - 2.1.0) <CB63147A-C9DC-308B-8CA1-EE92A5042E8E> /Applications/RoboPaint.app/Contents/MacOS/RoboPaint
       0x1069fe000 -        0x106a7c6a7  dyld (625.13) <D6387150-2FB8-3066-868D-72E1B1C43982> /usr/lib/dyld

Model: MacBookAir6,2, BootROM MBA61.0107.B00, 2 processors, Intel Core i7, 1.7 GHz, 8 GB, SMC 2.13f15
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
Bluetooth: Version 6.0.8f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: EiBotBoard,
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6
```

looks signature-related!

**Comment by oskay** [comment]
Yes, it's the signature.

**Comment by lalo** [comment]
I wonder if this might help https://developer.apple.com/developer-id/

**Comment by oskay** [comment]
We are aware of the method -- it's been signed in the past -- but there has been some kind of an issue with the setup on @techninja's computer.

**Comment by oskay** [comment]
Since this still seems to be an issue, I've gone ahead and signed a copy of v2.1.0, which I'm linking here: https://evilmadscience.s3.amazonaws.com/wiki/watercolor/software/RoboPaint.app.zip

Would one or two folks be willing to test and see if this works? (If so, I'll replace the download in the release with this one.)

**Comment by lalo** [comment]
@oskay does not work on my mac os 10.13.6, same error

**Comment by oskay** [comment]
@lalo Can you please say which error you are getting? We tested downloading on a different computer here and didn't have an issue.

**Comment by lalo** [comment]
<img width="532" alt="screen shot 2018-10-19 at 9 19 21 pm" src="https://user-images.githubusercontent.com/575454/47251159-bc4d8000-d3e4-11e8-8e39-f60b81c49e64.png">

```Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libnode.dylib
  Referenced from: /private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/B83A4C96-E526-4220-B6F9-7EB2F0C0974D/d/RoboPaint.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: no suitable image found.  Did find:
	/private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/B83A4C96-E526-4220-B6F9-7EB2F0C0974D/d/RoboPaint.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: code signature invalid for '/private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/B83A4C96-E526-4220-B6F9-7EB2F0C0974D/d/RoboPaint.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib'

	/private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/B83A4C96-E526-4220-B6F9-7EB2F0C0974D/d/RoboPaint.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: stat() failed with errno=45

Binary Images:
       0x109fa1000 -        0x109fa1ff7 +robopaint-main (2.1.0 - 2.1.0) <CB63147A-C9DC-308B-8CA1-EE92A5042E8E> /var/folders/*/RoboPaint.app/Contents/MacOS/RoboPaint
       0x109fac000 -        0x10dc31f73 +com.github.electron.framework (0) <64946C63-97A0-3AD6-BDBF-6CF9FE148113> /var/folders/*/RoboPaint.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x10e27b000 -        0x10e295fff +com.github.Squirrel (1.0 - 1) <4C459C36-AFB6-3B8A-8FEC-76C192C17E30> /var/folders/*/RoboPaint.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x10e2be000 -        0x10e321ff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /var/folders/*/RoboPaint.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x10e39e000 -        0x10e3b2fff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /var/folders/*/RoboPaint.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x112a39000 -        0x112a83acf  dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld
    0x7fff4860b000 -     0x7fff4860bfff  com.apple.Carbon (158 - 158) <F8B370D9-2103-3276-821D-ACC756167F86> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff546b4000 -     0x7fff546b4fff  com.apple.quartzframework (1.5 - 21) <DCEB0FCC-2C32-3D02-8752-7B6FA009AB85> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff546b5000 -     0x7fff54901ff7  com.apple.QuartzCore (1.11 - 584.62) <1950D993-DE48-3C97-95A5-66D98BDFC95D> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff55137000 -     0x7fff55462fff  com.apple.security (7.0 - 58286.70.7) <9FC166E1-14D0-305C-A086-02B9E83F547E> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff554f0000 -     0x7fff55520fff  com.apple.securityinterface (10.0 - 55109.50.6) <3C20BE54-8115-3C7B-9719-F746A9EBF72B> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff6eec3000 -     0x7fff6eec4ffb  libSystem.B.dylib (1252.50.4) <CD555F3B-FDDB-35E5-A2FB-FBBF3D62031A> /usr/lib/libSystem.B.dylib
    0x7fff6f0f8000 -     0x7fff6f14efff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
```

**Comment by oskay** [comment]
Wow-- a completely different error. 

Thank you;  I'll look into this.

**Comment by oskay** [comment]
Here's an updated snapshot to try:
https://evilmadscience.s3.amazonaws.com/wiki/watercolor/software/RoboPaint.zip

**Comment by lalo** [comment]
It loads but then has an initialization error, thanks for debugging all this @oskay. Is there something I need to install before hand? Just want to make sure its not an error on my side.

<img width="1246" alt="screen shot 2018-10-20 at 10 14 14 am" src="https://user-images.githubusercontent.com/575454/47258515-efc5f400-d450-11e8-93c4-879eafb245f3.png">

```EROFS: read-only file system, open '/private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/C28990B8-EFC9-4F76-88D8-D3514DD87D97/d/RoboPaint.app/Contents/Resources/app/node_modules/cncserver/config.ini'

Error: EROFS: read-only file system, open '/private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/C28990B8-EFC9-4F76-88D8-D3514DD87D97/d/RoboPaint.app/Contents/Resources/app/node_modules/cncserver/config.ini'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at exports.File.File.saveSync (/private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/C28990B8-EFC9-4F76-88D8-D3514DD87D97/d/RoboPaint.app/Contents/Resources/app/node_modules/nconf/lib/nconf/stores/file.js:93:6)
    at saveStoreSync (/private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/C28990B8-EFC9-4F76-88D8-D3514DD87D97/d/RoboPaint.app/Contents/Resources/app/node_modules/nconf/lib/nconf/provider.js:479:23)
    at Array.reduce (native)
    at exports.Provider.Provider.save (/private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/C28990B8-EFC9-4F76-88D8-D3514DD87D97/d/RoboPaint.app/Contents/Resources/app/node_modules/nconf/lib/nconf/provider.js:521:31)
    at /private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/C28990B8-EFC9-4F76-88D8-D3514DD87D97/d/RoboPaint.app/Contents/Resources/app/node_modules/cncserver/src/cncserver.settings.js:49:25
    at /private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/C28990B8-EFC9-4F76-88D8-D3514DD87D97/d/RoboPaint.app/Contents/Resources/app/node_modules/nconf/lib/nconf/provider.js:406:32
    at /private/var/folders/9l/rz1znw6x1s316tr5rmwhqvv80000gn/T/AppTranslocation/C28990B8-EFC9-4F76-88D8-D3514DD87D97/d/RoboPaint.app/Contents/Resources/app/node_modules/async/lib/async.js:52:16```

**Comment by oskay** [comment]
@techninja, any idea what this one is about?

Also, if you can give me a copy that _has  not_ been signed, it may be easier for me to conduct the signing.  I can also share my signing script with you-- if there's any chance that it would help to sign from the CLI rather than automatically.

**Comment by lalo** [comment]
Looks like its trying to write something without the permission to do it, possibly related to not having permissions on the /private/ folder.

**Comment by oskay** [comment]
I've tested it here on computers running 10.11.6, 10.13.5, and 10.14, and it appears to be working correctly on each of them.

I also don't have write access on /private/, so that's not it (or at least, not the root cause of the problem).

**Comment by lalo** [comment]
@jrheard can you test with the latest binary that @oskay shared? I'm know curious if its something on my side. 

Also Oskay, do you have the key somewhere on that computer that the app is able to function correctly because it has the developer or debug stuff installed also so it can figure things out automatically? Maybe try with another user that doesn't have access to wherever you develop the app.

**Comment by oskay** [comment]
I don't have debug tools for RoboPaint; I'm not the author of it, and don't know much about how it is built. 

The three computers that I tested on are my own (yes, development) computer that I use to sign things, as well as two non-developer computers, with different OS versions, neither of which has any access to signing tools.

**Comment by jrheard** [comment]
same behavior on my machine, big red error box that says

```
EROFS: read-only file system, open '/private/var/folders/zl/bh7pbyz95rg7pmcvcc_f_kdm0000gn/T/AppTranslocation/CB578BF1-A6E6-4BA0-9703-ED351A3144FF/d/RoboPaint 2.app/Contents/Resources/app/node_modules/cncserver/config.ini'

Error: EROFS: read-only file system, open '/private/var/folders/zl/bh7pbyz95rg7pmcvcc_f_kdm0000gn/T/AppTranslocation/CB578BF1-A6E6-4BA0-9703-ED351A3144FF/d/RoboPaint 2.app/Contents/Resources/app/node_modules/cncserver/config.ini'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at exports.File.File.saveSync (/private/var/folders/zl/bh7pbyz95rg7pmcvcc_f_kdm0000gn/T/AppTranslocation/CB578BF1-A6E6-4BA0-9703-ED351A3144FF/d/RoboPaint 2.app/Contents/Resources/app/node_modules/nconf/lib/nconf/stores/file.js:93:6)
    at saveStoreSync (/private/var/folders/zl/bh7pbyz95rg7pmcvcc_f_kdm0000gn/T/AppTranslocation/CB578BF1-A6E6-4BA0-9703-ED351A3144FF/d/RoboPaint 2.app/Contents/Resources/app/node_modules/nconf/lib/nconf/provider.js:479:23)
    at Array.reduce (native)
    at exports.Provider.Provider.save (/private/var/folders/zl/bh7pbyz95rg7pmcvcc_f_kdm0000gn/T/AppTranslocation/CB578BF1-A6E6-4BA0-9703-ED351A3144FF/d/RoboPaint 2.app/Contents/Resources/app/node_modules/nconf/lib/nconf/provider.js:521:31)
    at /private/var/folders/zl/bh7pbyz95rg7pmcvcc_f_kdm0000gn/T/AppTranslocation/CB578BF1-A6E6-4BA0-9703-ED351A3144FF/d/RoboPaint 2.app/Contents/Resources/app/node_modules/cncserver/src/cncserver.settings.js:49:25
    at /private/var/folders/zl/bh7pbyz95rg7pmcvcc_f_kdm0000gn/T/AppTranslocation/CB578BF1-A6E6-4BA0-9703-ED351A3144FF/d/RoboPaint 2.app/Contents/Resources/app/node_modules/nconf/lib/nconf/provider.js:406:32
    at /private/var/folders/zl/bh7pbyz95rg7pmcvcc_f_kdm0000gn/T/AppTranslocation/CB578BF1-A6E6-4BA0-9703-ED351A3144FF/d/RoboPaint 2.app/Contents/Resources/app/node_modules/async/lib/async.js:52:16
```

**Comment by oskay** [comment]
@jrheard:
Did you rename the app?

**Comment by oskay** [comment]
@jrheard and @lalo:
Did you copy RoboPaint.app to /Applications before launching?

**Comment by lalo** [comment]
@oskay you are correct. The error showed when launched from not /Applications. It launches correctly in /Applications folder. Sorry :\ and thanks for helping out!

**Comment by oskay** [comment]
Whoa! That was a _long shot_! @jrheard ?

**Comment by jrheard** [comment]
Same, I was running it from downloads - afk until tomorrow so can’t try
from applications today, but I’m sure it was the same issue!

**Comment by oskay** [comment]
Please let us know how it turns out when you have a chance. Thanks!

**Comment by jrheard** [comment]
same result: when i move robopaint to /Applications, it runs fine. i don't have a bot handy to test the program's full functionality with, but it definitely no longer crashes and appears to be in working order!

**Comment by oskay** [comment]
Fantastic. 

Thank you both @lalo and @jrheard for your patience and testing.

**Comment by jasoncharney** [comment]
@oskay 's posted version worked for me when I copied it to my Applications folder while the Github release still is damaged. I'm running it in Mojave, 10.14.1.

**Comment by oskay** [comment]
I've updated  the release with this version.
