### ISSUE TITLE
Other bots?

### ISSUE THREAD

**Issue by JellaFella** [evil-mad/robopaint#297]
I'm attempting to use robopaint so I can write APIs for the iDraw, an AxiDraw knockoff. Robopaint RT controls the bot just fine, while robopaint itself doesn't recognize it, and therefore can't connect to it. Any solutions?

**Comment by oskay** [comment]
You can add additional machine types by adding a new .ini file within cncserver/machine_types.

**Comment by JellaFella** [comment]
Would any .ini file work? What information needs to be in it, and in what format? I assume this is posted somewhere, but I can't find it.

**Comment by oskay** [comment]
Start with one of the files there, and modify as needed.
