### ISSUE TITLE
Mac OS X Catalina? Edit: should be OK! ✅

### ISSUE THREAD

**Issue by forresto** [evil-mad/robopaint#301]
I just fired up Robopaint 2.1.0-beta and it works, and now I'm worried about updating to Mac OS X Catalina. Has anybody done it with success?

I guess I'll guinea pig in the next weeks....

**Comment by oskay** [comment]
Tested, appears to work under Catalina.

I have not performed comprehensive testing; if you do encounter things that don't work, please open specific issues for them.
